let users = [{ "id": 1, "first_name": "Edie", "last_name": "Dandy", "email": "edandy0@wired.com", "gender": "Female" },
{ "id": 2, "first_name": "Arlina", "last_name": "Firpo", "email": "afirpo1@webeden.co.uk", "gender": "Genderfluid" },
{ "id": 3, "first_name": "Isabelita", "last_name": "Yesenev", "email": "iyesenev2@weather.com", "gender": "Genderfluid" },
{ "id": 4, "first_name": "Fanchette", "last_name": "Counter", "email": "fcounter3@exblog.jp", "gender": "Female" },
{ "id": 5, "first_name": "Alaric", "last_name": "Peascod", "email": "apeascod4@webmd.com", "gender": "Male" },
{ "id": 6, "first_name": "Orv", "last_name": "Cleyburn", "email": "ocleyburn5@virginia.edu", "gender": "Male" },
{ "id": 7, "first_name": "Drucy", "last_name": "Klossek", "email": "dklossek6@ft.com", "gender": "Female" },
{ "id": 8, "first_name": "Rozalin", "last_name": "Scones", "email": "rscones7@yellowpages.com", "gender": "Female" },
{ "id": 9, "first_name": "Nikoletta", "last_name": "Wenderoth", "email": "nwenderoth8@imdb.com", "gender": "Female" },
{ "id": 10, "first_name": "Missy", "last_name": "Daintier", "email": "mdaintier9@earthlink.net", "gender": "Female" },
{ "id": 11, "first_name": "Spencer", "last_name": "Cabel", "email": "scabela@bravesites.com", "gender": "Male" },
{ "id": 12, "first_name": "Korella", "last_name": "Tuffield", "email": "ktuffieldb@dailymail.co.uk", "gender": "Female" },
{ "id": 13, "first_name": "Sayer", "last_name": "Richen", "email": "srichenc@microsoft.com", "gender": "Male" },
{ "id": 14, "first_name": "Ozzy", "last_name": "Kerne", "email": "okerned@php.net", "gender": "Male" },
{ "id": 15, "first_name": "Muriel", "last_name": "Murdoch", "email": "mmurdoche@ftc.gov", "gender": "Female" },
{ "id": 16, "first_name": "Lorrie", "last_name": "Crocumbe", "email": "lcrocumbef@imageshack.us", "gender": "Female" },
{ "id": 17, "first_name": "Derward", "last_name": "Burtonwood", "email": "dburtonwoodg@qq.com", "gender": "Male" },
{ "id": 18, "first_name": "Atlanta", "last_name": "Gristhwaite", "email": "agristhwaiteh@ocn.ne.jp", "gender": "Female" },
{ "id": 19, "first_name": "Elliot", "last_name": "Ruddin", "email": "eruddini@examiner.com", "gender": "Male" },
{ "id": 20, "first_name": "Neely", "last_name": "Mugglestone", "email": "nmugglestonej@mapy.cz", "gender": "Female" },
{ "id": 21, "first_name": "Felicio", "last_name": "Klesl", "email": "fkleslk@creativecommons.org", "gender": "Male" },
{ "id": 22, "first_name": "Raff", "last_name": "Castagnone", "email": "rcastagnonel@geocities.com", "gender": "Male" },
{ "id": 23, "first_name": "Evangeline", "last_name": "Fraschetti", "email": "efraschettim@flavors.me", "gender": "Female" },
{ "id": 24, "first_name": "Morgan", "last_name": "Drinkeld", "email": "mdrinkeldn@weebly.com", "gender": "Female" },
{ "id": 25, "first_name": "Itch", "last_name": "Emeline", "email": "iemelineo@va.gov", "gender": "Male" },
{ "id": 26, "first_name": "Tony", "last_name": "Mudge", "email": "tmudgep@tumblr.com", "gender": "Male" },
{ "id": 27, "first_name": "Cassandra", "last_name": "Warrillow", "email": "cwarrillowq@stanford.edu", "gender": "Female" },
{ "id": 28, "first_name": "Kelcy", "last_name": "Duffin", "email": "kduffinr@dion.ne.jp", "gender": "Female" },
{ "id": 29, "first_name": "Laurens", "last_name": "McArdell", "email": "lmcardells@prweb.com", "gender": "Male" },
{ "id": 30, "first_name": "Aguie", "last_name": "Beenham", "email": "abeenhamt@earthlink.net", "gender": "Male" },
{ "id": 31, "first_name": "Wat", "last_name": "Biernat", "email": "wbiernatu@japanpost.jp", "gender": "Male" },
{ "id": 32, "first_name": "Silvain", "last_name": "O'Giany", "email": "sogianyv@cisco.com", "gender": "Male" },
{ "id": 33, "first_name": "Nickolas", "last_name": "de Almeida", "email": "ndealmeidaw@pen.io", "gender": "Male" },
{ "id": 34, "first_name": "Channa", "last_name": "Leser", "email": "cleserx@diigo.com", "gender": "Female" },
{ "id": 35, "first_name": "Silvester", "last_name": "Delnevo", "email": "sdelnevoy@1und1.de", "gender": "Male" },
{ "id": 36, "first_name": "Justinian", "last_name": "Goulthorp", "email": "jgoulthorpz@symantec.com", "gender": "Male" },
{ "id": 37, "first_name": "Lenna", "last_name": "Linscott", "email": "llinscott10@cbsnews.com", "gender": "Female" },
{ "id": 38, "first_name": "Ellette", "last_name": "Kennicott", "email": "ekennicott11@google.es", "gender": "Female" },
{ "id": 39, "first_name": "Wallache", "last_name": "Shellum", "email": "wshellum12@ifeng.com", "gender": "Male" },
{ "id": 40, "first_name": "Jerrilee", "last_name": "Pinck", "email": "jpinck13@instagram.com", "gender": "Female" },
{ "id": 41, "first_name": "Clareta", "last_name": "Brafferton", "email": "cbrafferton14@spotify.com", "gender": "Female" },
{ "id": 42, "first_name": "Tristan", "last_name": "Newburn", "email": "tnewburn15@ox.ac.uk", "gender": "Male" },
{ "id": 43, "first_name": "Joelle", "last_name": "Insole", "email": "jinsole16@issuu.com", "gender": "Female" },
{ "id": 44, "first_name": "Antonella", "last_name": "Dumphry", "email": "adumphry17@friendfeed.com", "gender": "Female" },
{ "id": 45, "first_name": "Leanor", "last_name": "Godleman", "email": "lgodleman18@multiply.com", "gender": "Female" },
{ "id": 46, "first_name": "Kristopher", "last_name": "Mompesson", "email": "kmompesson19@istockphoto.com", "gender": "Male" },
{ "id": 47, "first_name": "Killie", "last_name": "Ezzell", "email": "kezzell1a@discuz.net", "gender": "Male" },
{ "id": 48, "first_name": "Rustin", "last_name": "Kerslake", "email": "rkerslake1b@cdbaby.com", "gender": "Male" },
{ "id": 49, "first_name": "Aggi", "last_name": "Gresswell", "email": "agresswell1c@nytimes.com", "gender": "Female" },
{ "id": 50, "first_name": "Reiko", "last_name": "Lys", "email": "rlys1d@google.co.jp", "gender": "Female" }]


for (user of users) {
    console.log(user.email)
}